### ISSUE TITLE
pebble watch caller id not showing

### ISSUE THREAD

**Issue by ganeeesh02** [pebble-dev/wiki#5]
pebble watch caller id not working on android 9 and it is display as "unknown".

**Comment by jwise** [comment]
it sure does!

**Comment by vsdimov** [comment]
Is it really that hard for the developers to fix this issue? The problem is present for almost a year now and no solution yet? The "Dialer for Pebble" workaround doesn't always work either.

**Comment by matopeto** [comment]
There are no pebble developers left /-:

**Comment by XDjackieXD** [comment]
The Problem is that we don't have the sourcecode for the app and the pebble firmware. So fixing it is a bit like poking in the dark in the hopes of fixing the bug. I can recommend Gadgetbridge as replacement for the Pebble app which works without problems (but lacks a few features)

**Comment by ishotjr** [comment]
@vsdimov workarounds are being investigated. Stay tuned! 🔜

**Comment by jwise** [comment]
Who is investigating the workaround?  Without patching the app, it seems unlikely this is fixable.  Binary-patching the app is not impossible but we can't update it in the store.

**Comment by KonradIT** [comment]
Patching it via APKtool, if the fix can be applied in the androidmanifest.xml , smali editing is also a possibility. And then signing the app with our own keys since there will be no more play store updates.

**Comment by ishotjr** [comment]
> Who is investigating the workaround?

@jwise me!  Will of course share progress as it's made! :bowtie:

**Comment by jwise** [comment]
![](http://nyus.joshuawise.com/sendit.jpg)
