### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by matejdro** [pebble-dev/wiki#6]
Many of the links on the https://github.com/pebble-dev/wiki/wiki are dead, poing to official sources that are down.

Maybe a cleanup is in order?

**Comment by g-berthiaume** [comment]
+1 for this

**Comment by aveao** [comment]
Hey all, I just updated all official links that I could see that were not there as references (API outputs etc).

I'll be closing this issue now, but please feel free to mention any links you see that I may have missed and I'll try to find an archived version.
