### ISSUE TITLE
pebble app not available on IOS now

### ISSUE THREAD

**Issue by alirnz** [pebble-dev/wiki#7]
any way to download pebble app on IOS device (iphone) pebble watch also resett so unable to connect watch with phone

**Comment by Willow-Systems** [comment]
This was resolved early september. As per [this reddit thread](https://old.reddit.com/r/pebble/comments/czserq/pebble_back_in_the_ios_app_store_thanks_to_our/) the app can be downloaded [here](https://apps.apple.com/us/app/pebble/id957997620)

**Comment by yaomtc** [comment]
That app isn't under the control of Rebble, is it?

Also, could someone remind me what the URL parameter is to get the PBK file for a Pebble app? It was developer mode or something...

**Comment by sGerli** [comment]
No, it’s not under Rebble control, but it’s been available for a while

**Comment by yaomtc** [comment]
Found the answer to the other question myself: &dev_settings=true. Wish I didn't have to do this, though.
